# Generated by Django 5.1.15 on 2026-09-19 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('religion', models.CharField(blank=True, max_length=40)),
                ('nationality', models.CharField(blank=True, max_length=40)),
                ('place_of_birth', models.CharField(blank=True, max_length=60)),
                ('last_school', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(blank=True, max_length=40, verbose_name='Medium of instruction')),
                ('reason_for_leaving', models.CharField(blank=True, max_length=150)),
                ('residential_address', models.CharField(max_length=200)),
                ('current_address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=120)),
                ('guardian_name', models.CharField(max_length=60)),
                ('guardian_email', models.EmailField(blank=True, max_length=120)),
                ('tc', models.FileField(upload_to='admissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Transfer certificate')),
                ('marks', models.FileField(upload_to='admissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Marks card / transcripts')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes. Not shown publicly.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('year', models.CharField(help_text='e.g. "2024-25"', max_length=20)),
                ('title', models.CharField(max_length=80)),
                ('body', models.CharField(blank=True, help_text='The awarding body or event.', max_length=120)),
                ('image', models.FileField(blank=True, upload_to='awards/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg', 'gif'])])),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='School Brochure', max_length=80)),
                ('file', models.FileField(upload_to='brochures/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_active', models.BooleanField(default=True, help_text='Only one brochure is active at a time. Ticking this un-ticks the others.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('Admissions & Registration', 'Admissions & Registration'), ('Campus Visit / Tour', 'Campus Visit / Tour'), ('Fees & Scholarships', 'Fees & Scholarships'), ('Transport & Facilities', 'Transport & Facilities'), ('Careers at ICS', 'Careers at ICS'), ('Something else', 'Something else')], max_length=40)),
                ('message', models.TextField(max_length=1000)),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once the office has replied.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes. Not shown publicly.')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('title', models.CharField(help_text='Shown on the tile and popup.', max_length=80)),
                ('caption', models.TextField(blank=True, help_text='Shown in the popup under the title.', max_length=300)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Academics', 'Academics'), ('Events', 'Events'), ('Campus', 'Campus')], help_text='Drives the filter tabs.', max_length=20)),
                ('image', models.FileField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg', 'gif'])])),
                ('size', models.CharField(choices=[('tall', 'Tall — full height tile'), ('mid', 'Medium'), ('short', 'Short')], default='mid', help_text='Tile height in the collage. Mix these for a natural layout.', max_length=10)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('name', models.CharField(help_text='e.g. "Science Faculty" or a name.', max_length=80)),
                ('role', models.CharField(help_text='Shown in bold under the name.', max_length=80)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('qualification', models.CharField(blank=True, help_text='Shown beside the accent rule.', max_length=120)),
                ('bio', models.TextField(blank=True, help_text='Revealed when the card is clicked.', max_length=400)),
                ('photo', models.FileField(blank=True, help_text='Portrait. Roughly 4:3 works best.', upload_to='people/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg', 'gif'])])),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Indiranagar Cambridge School', max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=120)),
                ('email_hr', models.EmailField(blank=True, max_length=120, verbose_name='HR email')),
                ('hours_week', models.CharField(blank=True, max_length=60)),
                ('hours_sat', models.CharField(blank=True, max_length=60)),
                ('maps_url', models.URLField(blank=True, max_length=300)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('label', models.CharField(help_text='e.g. "Founded"', max_length=40)),
                ('value', models.IntegerField(help_text='The number it counts to, e.g. 1979.')),
                ('count_from', models.IntegerField(blank=True, help_text='Leave blank to count up from 0. Set it to count DOWN (the founding year counts down from the current year).', null=True)),
                ('suffix', models.CharField(blank=True, help_text='Appended to the number, e.g. "+".', max_length=5)),
                ('grouped', models.BooleanField(default=True, help_text='Untick for years, so 1979 does not render as 1,979.', verbose_name='Thousands separator')),
                ('icon', models.CharField(choices=[('calendar', 'Calendar'), ('users', 'People'), ('award', 'Award'), ('pin', 'Location pin'), ('flask', 'Science flask'), ('palette', 'Arts palette')], default='award', max_length=20)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
