# Generated by Django 5.1.15 on 2026-10-03 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='academics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg', 'gif'])])),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='Image description')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('tag', models.CharField(blank=True, help_text='Outlined label, e.g. "1986".', max_length=40)),
                ('badge', models.CharField(blank=True, help_text='Solid label, e.g. "TODAY".', max_length=40)),
                ('image', models.FileField(blank=True, upload_to='chapters/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg', 'gif'])])),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='Image description')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField(blank=True, help_text='Leave a blank line between paragraphs. Leave empty to show only the title and photo.')),
                ('tagline', models.CharField(blank=True, help_text='Bold closing line.', max_length=120)),
                ('image', models.FileField(blank=True, upload_to='facilities/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg', 'gif'])])),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='Image description')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Where this appears. Do not change.', unique=True)),
                ('label', models.CharField(help_text='Which page and section this is.', max_length=80)),
                ('eyebrow', models.CharField(blank=True, help_text='Small text above the title (badge / name).', max_length=120)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('subtitle', models.CharField(blank=True, help_text='Line under the title, or a tagline.', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Leave a blank line between paragraphs.')),
                ('quote', models.CharField(blank=True, max_length=300)),
                ('image', models.FileField(blank=True, upload_to='sections/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg', 'gif'])])),
            ],
            options={
                'verbose_name': 'Page text & image',
                'verbose_name_plural': 'Page text & images',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('title', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=300)),
                ('link', models.CharField(default='/academics', help_text='Page it links to, e.g. "/academics".', max_length=100)),
                ('icon', models.CharField(choices=[('flask', 'Science flask'), ('palette', 'Arts palette'), ('award', 'Award'), ('users', 'People')], default='flask', max_length=20)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='experience',
            field=models.CharField(blank=True, help_text='e.g. "10+ Years"', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='content_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_emails',
            field=models.CharField(blank=True, help_text='Admission and contact form submissions are emailed here. Separate several addresses with commas.', max_length=500, verbose_name='Send form submissions to'),
        ),
        migrations.AlterField(
            model_name='award',
            name='body',
            field=models.CharField(blank=True, help_text='The awarding body or event.', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, help_text='Shown in the popup when the card is clicked. Leave a blank line between paragraphs.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, help_text='Portrait photo.', upload_to='people/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='person',
            name='qualification',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(help_text='Designation, e.g. "Hindi Educator".', max_length=80),
        ),
        migrations.CreateModel(
            name='StageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('tag', models.CharField(help_text='e.g. "Grades 1-2"', max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=200)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.academicstage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
