# Generated by Django 5.1.15 on 2026-10-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_site_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='X (Twitter)'),
        ),
    ]
