# Generated by Django 5.1.15 on 2026-10-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_twitter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brevo_api_key',
            field=models.CharField(blank=True, help_text='From brevo.com → SMTP & API → API Keys. Leave blank to keep the saved key (or to use the BREVO_API_KEY server setting).', max_length=200, verbose_name='Brevo API key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_sender',
            field=models.EmailField(blank=True, help_text='Must be a sender verified in Brevo (Senders, Domains & Dedicated IPs → Senders). Blank uses the DEFAULT_FROM_EMAIL server setting.', max_length=120, verbose_name='Send emails from'),
        ),
    ]
